from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'submission.cpp'

PARTS = (
    'include/Protocol.hpp',
    'include/SystemConfig.hpp',
    'include/TaskTimeTable.hpp',
    'include/WorldState.hpp',
    'include/RemotePlacement.hpp',
    'include/SingletonScheduler.hpp',
    'include/DecodeBatchScheduler.hpp',
    'include/ScoreAwareScheduler.hpp',
    'include/AdaptiveScheduler.hpp',
    'include/MultiprocessorScheduler.hpp',
    'include/Scheduler.hpp',
    'src/SchedulerCore.hpp',
    'src/Protocol.cpp',
    'src/SystemConfig.cpp',
    'src/TaskTimeTable.cpp',
    'src/WorldState.cpp',
    'src/SingletonScheduler.cpp',
    'src/DecodeBatchScheduler.cpp',
    'src/ScoreAwareScheduler.cpp',
    'src/AdaptiveScheduler.cpp',
    'src/MultiprocessorScheduler.cpp',
    'src/main.cpp',
)

LOCAL_HEADERS = {Path(part).name for part in PARTS if part.endswith('.hpp')}
INCLUDE_PATTERN = re.compile(r'^\s*#include\s*[<\x22]([^>\x22]+)[>\x22]\s*$')


def prepare_part(relative_path: str) -> str:
    source = ROOT / relative_path
    kept_lines: list[str] = []

    for line in source.read_text(encoding='utf-8').splitlines():
        if line.strip() == '#pragma once':
            continue

        include = INCLUDE_PATTERN.match(line)
        if include and Path(include.group(1)).name in LOCAL_HEADERS:
            continue

        kept_lines.append(line.rstrip())

    body = '\n'.join(kept_lines).strip()
    return f'// ===== BEGIN {relative_path} =====\n{body}\n// ===== END {relative_path} ====='


def main() -> None:
    sections = [
        '// Generated by scripts/generate_submission.py. Do not edit this file directly.',
        '// Regenerate it after changing project sources.',
        *(prepare_part(part) for part in PARTS),
    ]

    with OUTPUT.open('w', encoding='utf-8', newline='\n') as submission:
        submission.write('\n\n'.join(sections))
        submission.write('\n')

    print(f'Generated {OUTPUT}')


if __name__ == '__main__':
    main()
