// Generated by scripts/generate_submission.py. Do not edit this file directly.

// Regenerate it after changing project sources.

// ===== BEGIN include/Protocol.hpp =====
#include <cstdint>
#include <iosfwd>
#include <optional>
#include <variant>
#include <vector>

/************************************/
/************** SERVERS *************/
/************************************/

enum class ServerType {
  Edge,
  Cloud
};

struct ServerId {
  ServerType type;
  int cloud_index; // Ignored when type == Edge
};

/*********************************/
/************* TASKS *************/
/*********************************/

struct PrefillPreTask {
  int remote;
  int rid;
};

struct PrefillProcTask {
  int layer_begin;
  int layer_end;
  int remote;
  int rid;
};

struct PrefillPostTask {
  int remote;
  int rid;
};

struct DecodePreTask {
  std::vector<int> rids;
};

struct DecodeProcTask {
  int remote;
  std::vector<int> rids;
};

struct DecodePostTask {
  std::vector<int> rids;
};

// TaskSpec: temporary work assigned to a computer
using TaskSpec = std::variant<
  PrefillPreTask,
  PrefillProcTask,
  PrefillPostTask,
  DecodePreTask,
  DecodeProcTask,
  DecodePostTask
>;

struct Assignment {
  ServerId server;
  TaskSpec task;
};

/**********************************/
/************* EVENTS *************/
/**********************************/

struct ArrivalEvent {
  int rid;
  int input_length;
  /* rid, input length */
};

struct TaskDoneEvent {
  ServerId server;
  TaskSpec task;
  double duration;
  /* server, task specification, duration */
};

enum class TransferDirection {
  Up,
  Down
};

enum class TransferStage {
  Prefill,
  Decode
};

// XDN <UP|DOWN> <remote> <size> <PRE|DEC> <m> <rid...>
struct TransferDoneEvent {
  TransferDirection direction;
  int remote;
  std::int64_t size_bytes;
  TransferStage stage;
  std::vector < int > rids;
  /* direction, remote, size, stage, rids */
};

struct FinishEvent {
  int rid;
  /* rid */
};

// Event: notification that something arrived or completed
using Event = std::variant<
  ArrivalEvent,
  TaskDoneEvent,
  TransferDoneEvent,
  FinishEvent
>;

/********************************/
/************* FRAME ************/
/********************************/

struct Frame {
  double timestamp;
  std::vector < Event > events;
};

std::optional < Frame > readFrame(std::istream& input);
void writeAssignments(std::ostream& output, const std::vector<Assignment>& assignments);
// ===== END include/Protocol.hpp =====

// ===== BEGIN include/SystemConfig.hpp =====
// times in ms, output rates in tokens/ms
#include <iosfwd>
#include <cstdint>

// K S latency_in_ms bandwidth_gbps bytes_per_token num_layers
// SLO1 SLO2 tp_UB tp_base dist_base w_tp w_c
struct SystemConfig {
  // Scoring parameters
  double SLO1;
  double SLO2;
  double tp_UB;
  double tp_base;
  double dist_base;
  double w_tp;
  double w_c;

  // System parameters
  double S;                   // Schedule Cost
  double latency_in_ms;
  double bandwidth_gbps;
  int K;
  int bytes_per_token;
  int num_layers;
};

double transferTime(const SystemConfig& config, std::int64_t len);
SystemConfig readSystemConfig(std::istream& input);
// ===== END include/SystemConfig.hpp =====

// ===== BEGIN include/TaskTimeTable.hpp =====
#include <iosfwd>
#include <vector>

// Read an integer N, then N rows of 7 values; no response is expected:
// batch_size  prefill_pre  prefill_proc  prefill_post  decode_pre  decode_proc  decode_post

// batch_size:    the number of requests grouped into one task
// prefill:       the input stage
// decode:        output steps

// a more advanced scheduler will use the complete task-time table, including values between listed rows.

struct TaskTimeRow {
  int batch_size; // L_in: vals are distinct positive integers in [1, 4096]

  double prefill_pre;
  double prefill_proc;
  double prefill_post;

  double decode_pre;
  double decode_proc;
  double decode_post;
};

struct TaskTimeTable {
  std::vector<TaskTimeRow> rows;
};

struct TimingPoint {
  int batch_size;
  double duration;
};

struct TimingCurve {
  std::vector < TimingPoint > points;
};

struct TimingCurves {
  TimingCurve prefill_pre;
  TimingCurve prefill_proc;
  TimingCurve prefill_post;
  TimingCurve decode_pre;
  TimingCurve decode_proc;
  TimingCurve decode_post;
};

TaskTimeTable readTaskTimeTable(std::istream& input);
TimingCurves buildTimingCurves(const TaskTimeTable& table);
double interpolate(const TimingCurve& curve, int size);
// ===== END include/TaskTimeTable.hpp =====

// ===== BEGIN include/WorldState.hpp =====
#include <cstddef>
#include <optional>
#include <vector>

// RequestState: current position of that request
enum class RequestState {
  ReadyPrefillPre,
  WaitingPrefillPreDone,
  WaitingPrefillUpload,

  ReadyPrefillProc,
  WaitingPrefillProcDone,
  WaitingPrefillDownload,

  ReadyPrefillPost,
  WaitingPrefillPostDone,

  ReadyDecodePre,
  WaitingDecodePreDone,
  WaitingDecodeUpload,

  ReadyDecodeProc,
  WaitingDecodeProcDone,
  WaitingDecodeDownload,

  ReadyDecodePost,
  WaitingDecodePostDone,

  Finished
};

// Request: persistent end-to-end workload
struct Request {
  int input_length;
  double arrival_time;

  std::optional<int> remote;
  int next_prefill_layer = 0;
  int tokens_produced = 0;

  RequestState state;
};

struct ServerState  {
  bool busy = false;
};

struct WorldState {
  double current_time = 0.0;

  ServerState edge;
  std::vector<ServerState> clouds;
  std::vector<Request> requests;

  explicit WorldState(int cloud_count)
    : clouds(static_cast<std::size_t>(cloud_count)) {}
};

void applyFrame(WorldState& world, const Frame& frame, int num_layers);
void startAssignment(WorldState& world, const Assignment& assignment, int num_layers);
// ===== END include/WorldState.hpp =====

// ===== BEGIN include/Scheduler.hpp =====
#include <vector>

struct DecodeBatchPolicy {
  std::vector<int> pre_by_ready_count;
  std::vector<int> proc_by_ready_count;
  std::vector<int> post_by_ready_count;
};

DecodeBatchPolicy buildDecodeBatchPolicy(const TimingCurves& curves, double assignment_cost, int max_batch_size = 4096);
std::vector<Assignment> chooseSingletonAssignments(const WorldState& world, int num_layers);
std::vector<Assignment> chooseBatchedAssignments(
  const WorldState& world, int num_layers, const DecodeBatchPolicy& batch_policy);
// ===== END include/Scheduler.hpp =====

// ===== BEGIN src/Protocol.cpp =====
#include <iostream>
#include <string>
#include <vector>
#include <variant>
#include <cassert>
#include <stdexcept>

std::vector<int> readRequestIds(std::istream& input) {
  int count;
  input >> count;
  assert(count >= 1);

  std::vector<int> rids(static_cast<std::size_t>(count));
  for (int& rid : rids) {
    input >> rid;
  }

  return rids;
}

ServerId readServer(std::istream& input) {
  std::string server_token;
  input >> server_token;
  if (server_token == "E") {
    return {ServerType::Edge, -1};
  }

  if (server_token.size() >= 2 && server_token.front() == 'C') {
    const int cloud_index = std::stoi(server_token.substr(1));
    return {ServerType::Cloud, cloud_index};
  }

  throw std::runtime_error("Unknown server");
}

TaskSpec readTaskSpec(std::istream& input) {
  int marker;
  std::string family, stage;
  input >> family >> stage;

  if (family == "P") {
    if (stage == "PRE") {
      PrefillPreTask task{};
      input >> task.remote >> task.rid;
      return task;
    }

    if (stage == "PROC") {
      PrefillProcTask task{};
      input
        >> task.layer_begin
        >> task.layer_end
        >> task.remote
        >> task.rid;
      return task;
    }

    if (stage == "POST") {
      PrefillPostTask task{};
      input >> task.remote >> task.rid;
      return task;
    }
  }

  if (family == "D") {
    if (stage == "PRE") {
      DecodePreTask task{};
      input >> marker;
      assert(marker == -1);
      task.rids = readRequestIds(input);
      return task;
    }

    if (stage == "PROC") {
      DecodeProcTask task{};
      input >> task.remote;
      task.rids = readRequestIds(input);
      return task;
    }

    if (stage == "POST") {
      DecodePostTask task{};
      input >> marker;
      assert(marker == -1);
      task.rids = readRequestIds(input);
      return task;
    }
  }

  throw std::runtime_error("Unknown task spec");
}

TransferDirection parseTransferDirection(const std::string& token) {
  if (token == "UP") return TransferDirection::Up;
  if (token == "DOWN") return TransferDirection::Down;
  throw std::runtime_error("Unknown transfer direction");
}

TransferStage parseTransferStage(const std::string& token) {
  if (token == "PRE") return TransferStage::Prefill;
  if (token == "DEC") return TransferStage::Decode;
  throw std::runtime_error("Unknown transfer stage");
}

Event readEvent(std::istream& input) {
  std::string type;
  input >> type;

  if (type == "ARR") {
    ArrivalEvent event{};
    input >> event.rid >> event.input_length;
    return event;
  }

  if (type == "TDN") {
    TaskDoneEvent event{};
    event.server = readServer(input);
    event.task = readTaskSpec(input);
    input >> event.duration;
    return event;
  }

  if (type == "XDN") {
    TransferDoneEvent event{};
    std::string direction_token;
    std::string stage_token;

    input
      >> direction_token
      >> event.remote
      >> event.size_bytes
      >> stage_token;

    event.direction = parseTransferDirection(direction_token);
    event.stage = parseTransferStage(stage_token);
    event.rids = readRequestIds(input);

    return event;
  }

  if (type == "FIN") {
    FinishEvent event{};
    input >> event.rid;
    return event;
  }

  throw std::runtime_error("Unknown event type");
}

std::optional<Frame> readFrame(std::istream& input) {
  std::string timestamp_token;

  if (!(input >> timestamp_token) || timestamp_token == "END") {
    return std::nullopt;
  }

  Frame frame{};
  frame.timestamp = std::stod(timestamp_token);

  int event_count;
  input >> event_count;
  assert(event_count >= 0);

  frame.events.reserve(static_cast<std::size_t>(event_count));

  for (int i = 0; i < event_count; ++i) {
    frame.events.push_back(readEvent(input));
  }

  return frame;
}

namespace {

template <typename... Visitors>
struct OutputVisitor : Visitors... {
  using Visitors::operator()...;
};

template <typename... Visitors>
OutputVisitor(Visitors...) -> OutputVisitor<Visitors...>;

void writeRequestIds(std::ostream& output, const std::vector<int>& rids) {
  output << rids.size();
  for (const int rid : rids) {
    output << ' ' << rid;
  }
}

void writeServer(std::ostream& output, const ServerId& server) {
  if (server.type == ServerType::Edge) {
    output << "E";
  } else {
    output << "C" << server.cloud_index;
  }
}

void writeTaskSpec(std::ostream& output, const TaskSpec& task) {
  std::visit(OutputVisitor{
    [&](const PrefillPreTask& value) {
      output << "P PRE " << value.remote << ' ' << value.rid;
    },
    [&](const PrefillProcTask& value) {
      output << "P PROC " << value.layer_begin << ' ' << value.layer_end << ' ' << value.remote << ' ' << value.rid;
    },
    [&](const PrefillPostTask& value) {
      output << "P POST " << value.remote << ' ' << value.rid;
    },
    [&](const DecodePreTask& value) {
      output << "D PRE -1 ";
      writeRequestIds(output, value.rids);
    },
    [&](const DecodeProcTask& value) {
      output << "D PROC " << value.remote << ' ';
      writeRequestIds(output, value.rids);
    },
    [&](const DecodePostTask& value) {
      output << "D POST -1 ";
      writeRequestIds(output, value.rids);
    },
  }, task);
}

} // namespace

void writeAssignments(std::ostream& output, const std::vector<Assignment>& assignments) {
  output << assignments.size() << '\n';

  for (const Assignment& assignment : assignments) {
    writeServer(output, assignment.server);
    output << ' ';
    writeTaskSpec(output, assignment.task);
    output << '\n';
  }
}
// ===== END src/Protocol.cpp =====

// ===== BEGIN src/SystemConfig.cpp =====
#include <istream>
#include <cassert>

// move this to correct file
double transferTime(const SystemConfig& config, std::int64_t len) {
  // for input transfer: len = L_in[i]
  // for output transfer:
  //   for output, use the per-remote computer local-to-remote transfer and
  //   per-group remote-to-local transfer sizes defined in Output Steps
  assert(config.latency_in_ms > 0);
  const std::int64_t data_bytes = len * config.bytes_per_token;
  return config.latency_in_ms + 8.0 * static_cast<double>(data_bytes)
    / (config.bandwidth_gbps * 1'000'000.0); // ms
}

SystemConfig readSystemConfig(std::istream& input) {
  SystemConfig config{};

  input >> config.K
    >> config.S
    >> config.latency_in_ms
    >> config.bandwidth_gbps
    >> config.bytes_per_token
    >> config.num_layers
    >> config.SLO1
    >> config.SLO2
    >> config.tp_UB
    >> config.tp_base
    >> config.dist_base
    >> config.w_tp
    >> config.w_c;

  return config;
}
// ===== END src/SystemConfig.cpp =====

// ===== BEGIN src/TaskTimeTable.cpp =====
#include <istream>
#include <vector>
#include <cassert>
#include <algorithm>

// Preconditions:
// - curve.points is nonempty
// - points are sorted by batch_size
// - no point has duration == -1
double interpolate(const TimingCurve& curve, int size) {
  assert(!curve.points.empty());
  if (size <= curve.points.front().batch_size) {
    return curve.points.front().duration;
  }

  if (curve.points.back().batch_size <= size) {
    return curve.points.back().duration;
  }

  for (std::size_t i = 0; i + 1 < curve.points.size(); ++i) {
    const TimingPoint& left = curve.points[i];
    const TimingPoint& right = curve.points[i + 1];

    if (left.batch_size <= size && size <= right.batch_size) {
      return left.duration
        + (size - left.batch_size)
        * (right.duration - left.duration)
        / (right.batch_size - left.batch_size);
    }
  }

  assert(false);
  return 0.0;
}

namespace {

using DurationMember = double TaskTimeRow::*;

void finalizeCurve(TimingCurve& curve) {
  assert(!curve.points.empty());
  std::sort(curve.points.begin(), curve.points.end(), [](const TimingPoint& a, const TimingPoint& b) {
    return a.batch_size < b.batch_size;
  });
}

TimingCurve makeTimingCurve(const TaskTimeTable& table, DurationMember member) {
  TimingCurve curve;
  curve.points.reserve(table.rows.size());
  for (const TaskTimeRow& row : table.rows) {
    const double duration = row.*member;

    if (duration != -1.0) {
      curve.points.push_back({row.batch_size, duration});
    }
  }

  finalizeCurve(curve);
  return curve;
}

} // namespace

TimingCurves buildTimingCurves(const TaskTimeTable& table) {
  return {
    .prefill_pre  = makeTimingCurve(table, &TaskTimeRow::prefill_pre),
    .prefill_proc = makeTimingCurve(table, &TaskTimeRow::prefill_proc),
    .prefill_post = makeTimingCurve(table, &TaskTimeRow::prefill_post),
    .decode_pre   = makeTimingCurve(table, &TaskTimeRow::decode_pre),
    .decode_proc  = makeTimingCurve(table, &TaskTimeRow::decode_proc),
    .decode_post  = makeTimingCurve(table, &TaskTimeRow::decode_post),
  };
}

TaskTimeTable readTaskTimeTable(std::istream& input) {
  int n;
  input >> n;
  TaskTimeTable table;
  table.rows.reserve(n);
  for (int i = 0; i < n; i++) {
    TaskTimeRow row{};
    input >> row.batch_size;
    input >> row.prefill_pre >> row.prefill_proc >> row.prefill_post;
    input >> row.decode_pre >> row.decode_proc >> row.decode_post;
    table.rows.push_back(row);
  }
  return table;
}
// ===== END src/TaskTimeTable.cpp =====

// ===== BEGIN src/WorldState.cpp =====
#include <cassert>
#include <variant>

namespace {

template <typename... Visitors>
struct Overloaded : Visitors... {
  using Visitors::operator()...;
};

template <typename... Visitors>
Overloaded(Visitors...) -> Overloaded<Visitors...>;

Request& getRequest(WorldState& world, int rid) {
  assert(rid >= 0);
  const auto index = static_cast<std::size_t>(rid);
  assert(index < world.requests.size());
  return world.requests.at(index);
}

ServerState& getServer(WorldState& world, const ServerId& server) {
  if (server.type == ServerType::Edge) {
    return world.edge;
  }

  assert(server.cloud_index >= 0);
  const auto index = static_cast<std::size_t>(server.cloud_index);
  assert(index < world.clouds.size());
  return world.clouds.at(index);
}

void assertEdgeServer(const ServerId& server) {
  assert(server.type == ServerType::Edge);
}

void assertCloudServer(const ServerId& server, int remote) {
  assert(server.type == ServerType::Cloud);
  assert(server.cloud_index == remote);
}

void assertRequestRemote(const Request& request, int remote) {
  assert(request.remote.has_value());
  assert(*request.remote == remote);
}

void applyArrival(WorldState& world, const ArrivalEvent& arrival) {
  assert(arrival.rid >= 0);
  assert(arrival.input_length > 0);

  const auto rid = static_cast<std::size_t>(arrival.rid);
  assert(rid == world.requests.size());

  world.requests.push_back({
    .input_length = arrival.input_length,
    .arrival_time = world.current_time,
    .remote = std::nullopt,
    .next_prefill_layer = 0,
    .tokens_produced = 0,
    .state = RequestState::ReadyPrefillPre,
  });
}

void applyTaskDone(WorldState& world, const TaskDoneEvent& event, int num_layers) {
  assert(num_layers > 0);

  ServerState& server = getServer(world, event.server);
  assert(server.busy);

  std::visit(Overloaded{
    [&](const PrefillPreTask& task) {
      assertEdgeServer(event.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::WaitingPrefillPreDone);
      assertRequestRemote(request, task.remote);
      request.state = RequestState::WaitingPrefillUpload;
    },
    [&](const PrefillProcTask& task) {
      assertCloudServer(event.server, task.remote);
      assert(task.layer_begin >= 0);
      assert(task.layer_begin < task.layer_end);
      assert(task.layer_end <= num_layers);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::WaitingPrefillProcDone);
      assertRequestRemote(request, task.remote);
      assert(request.next_prefill_layer == task.layer_begin);

      request.next_prefill_layer = task.layer_end;
      request.state = task.layer_end == num_layers
        ? RequestState::WaitingPrefillDownload
        : RequestState::ReadyPrefillProc;
    },
    [&](const PrefillPostTask& task) {
      assertEdgeServer(event.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::WaitingPrefillPostDone);
      assertRequestRemote(request, task.remote);
      request.state = RequestState::ReadyDecodePre;
    },
    [&](const DecodePreTask& task) {
      assertEdgeServer(event.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        Request& request = getRequest(world, rid);
        assert(request.state == RequestState::WaitingDecodePreDone);
        assert(request.remote.has_value());
        request.state = RequestState::WaitingDecodeUpload;
      }
    },
    [&](const DecodeProcTask& task) {
      assertCloudServer(event.server, task.remote);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        Request& request = getRequest(world, rid);
        assert(request.state == RequestState::WaitingDecodeProcDone);
        assertRequestRemote(request, task.remote);
        request.state = RequestState::WaitingDecodeDownload;
      }
    },
    [&](const DecodePostTask& task) {
      assertEdgeServer(event.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        Request& request = getRequest(world, rid);
        assert(request.state == RequestState::WaitingDecodePostDone);
        ++request.tokens_produced;
        request.state = RequestState::ReadyDecodePre;
      }
    },
  }, event.task);

  server.busy = false;
}

void applyTransferDone(WorldState& world, const TransferDoneEvent& event) {
  assert(event.remote >= 0);
  assert(static_cast<std::size_t>(event.remote) < world.clouds.size());
  assert(!event.rids.empty());

  if (event.stage == TransferStage::Prefill) {
    assert(event.rids.size() == 1);

    Request& request = getRequest(world, event.rids.front());
    assertRequestRemote(request, event.remote);

    if (event.direction == TransferDirection::Up) {
      assert(request.state == RequestState::WaitingPrefillUpload);
      request.state = RequestState::ReadyPrefillProc;
    } else {
      assert(request.state == RequestState::WaitingPrefillDownload);
      request.state = RequestState::ReadyPrefillPost;
    }

    return;
  }

  for (const int rid : event.rids) {
    Request& request = getRequest(world, rid);
    assertRequestRemote(request, event.remote);

    if (event.direction == TransferDirection::Up) {
      assert(request.state == RequestState::WaitingDecodeUpload);
      request.state = RequestState::ReadyDecodeProc;
    } else {
      assert(request.state == RequestState::WaitingDecodeDownload);
      request.state = RequestState::ReadyDecodePost;
    }
  }
}

void applyFinish(WorldState& world, const FinishEvent& finish) {
  Request& request = getRequest(world, finish.rid);
  assert(request.state == RequestState::ReadyDecodePre);
  assert(request.tokens_produced > 0);
  request.state = RequestState::Finished;
}

} // namespace

void applyFrame(WorldState& world, const Frame& frame, int num_layers) {
  assert(frame.timestamp >= world.current_time);
  world.current_time = frame.timestamp;

  // FIN is deliberately deferred. The statement guarantees that it appears
  // in the same frame as the final D POST TDN, and frame line order carries no
  // priority. Applying all other events first ensures Finished always wins.
  for (const Event& event : frame.events) {
    if (const ArrivalEvent* arrival = std::get_if<ArrivalEvent>(&event)) {
      applyArrival(world, *arrival);
    } else if (const TaskDoneEvent* task_done = std::get_if<TaskDoneEvent>(&event)) {
      applyTaskDone(world, *task_done, num_layers);
    } else if (const TransferDoneEvent* transfer_done = std::get_if<TransferDoneEvent>(&event)) {
      applyTransferDone(world, *transfer_done);
    }
  }

  for (const Event& event : frame.events) {
    if (const FinishEvent* finish = std::get_if<FinishEvent>(&event)) {
      applyFinish(world, *finish);
    }
  }
}

void startAssignment(WorldState& world, const Assignment& assignment, int num_layers) {
  assert(num_layers > 0);
  assert(num_layers > 0);

  ServerState& server = getServer(world, assignment.server);
  assert(!server.busy);

  std::visit(Overloaded{
    [&](const PrefillPreTask& task) {
      assertEdgeServer(assignment.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::ReadyPrefillPre);
      assert(!request.remote.has_value());

      assert(task.remote >= 0);
      assert(static_cast<std::size_t>(task.remote) < world.clouds.size());

      request.remote = task.remote;
      request.state = RequestState::WaitingPrefillPreDone;
    },
    [&](const PrefillProcTask& task) {
      assertCloudServer(assignment.server, task.remote);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::ReadyPrefillProc);
      assertRequestRemote(request, task.remote);

      assert(task.layer_begin == request.next_prefill_layer);
      assert(task.layer_begin >= 0);
      assert(task.layer_begin < task.layer_end);
      assert(task.layer_end <= num_layers);

      request.state = RequestState::WaitingPrefillProcDone;
    },
    [&](const PrefillPostTask& task) {
      assertEdgeServer(assignment.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::ReadyPrefillPost);
      assertRequestRemote(request, task.remote);

      request.state = RequestState::WaitingPrefillPostDone;
    },
    [&](const DecodePreTask& task) {
      assertEdgeServer(assignment.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        const Request& request = getRequest(world, rid);
        assert(request.state == RequestState::ReadyDecodePre);
        assert(request.remote.has_value());
      }

      for (const int rid : task.rids) {
        getRequest(world, rid).state = RequestState::WaitingDecodePreDone;
      }
    },
    [&](const DecodeProcTask& task) {
      assertCloudServer(assignment.server, task.remote);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        const Request& request = getRequest(world, rid);
        assert(request.state == RequestState::ReadyDecodeProc);
        assertRequestRemote(request, task.remote);
      }

      for (const int rid : task.rids) {
        getRequest(world, rid).state = RequestState::WaitingDecodeProcDone;
      }
    },
    [&](const DecodePostTask& task) {
      assertEdgeServer(assignment.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        const Request& request = getRequest(world, rid);
        assert(request.state == RequestState::ReadyDecodePost);
        assert(request.remote.has_value());
      }

      for (const int rid : task.rids) {
        getRequest(world, rid).state = RequestState::WaitingDecodePostDone;
      }
    },
  }, assignment.task);

  server.busy = true;
}
// ===== END src/WorldState.cpp =====

// ===== BEGIN src/Scheduler.cpp =====
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <limits>
#include <optional>
#include <utility>
#include <vector>

namespace {

std::optional<int> findFirstRequest(
  const WorldState& world, RequestState state, std::optional<int> remote = std::nullopt) {
  for (std::size_t i = 0; i < world.requests.size(); ++i) {
    const Request& request = world.requests[i];
    if (request.state != state) {
      continue;
    }
    if (remote.has_value() && request.remote != remote) {
      continue;
    }

    return static_cast<int>(i);
  }

  return std::nullopt;
}

std::vector<int> findRequests(
  const WorldState& world, RequestState state, std::optional<int> remote, std::size_t limit) {
  std::vector<int> rids;
  rids.reserve(std::min(limit, world.requests.size()));

  for (std::size_t i = 0; i < world.requests.size() && rids.size() < limit; ++i) {
    const Request& request = world.requests[i];
    if (request.state == state && (!remote.has_value() || request.remote == remote)) {
      rids.push_back(static_cast<int>(i));
    }
  }

  return rids;
}

int batchSizeForReadyCount(const std::vector<int>& choices, std::size_t ready_count) {
  assert(ready_count > 0);
  assert(choices.size() > 1);
  const std::size_t index = std::min(ready_count, choices.size() - 1);
  return choices[index];
}

std::vector<int> chooseDecodeRids(
  const WorldState& world,
  RequestState state,
  std::optional<int> remote,
  const std::vector<int>* batch_choices) {
  const std::size_t limit = batch_choices == nullptr ? 1 : std::numeric_limits<std::size_t>::max();
  std::vector<int> rids = findRequests(world, state, remote, limit);
  if (rids.empty() || batch_choices == nullptr) {
    return rids;
  }

  rids.resize(static_cast<std::size_t>(batchSizeForReadyCount(*batch_choices, rids.size())));
  return rids;
}

std::optional<Assignment> chooseEdgeAssignment(const WorldState& world, const DecodeBatchPolicy* batch_policy) {
  if (world.edge.busy) {
    return std::nullopt;
  }

  const std::vector<int>* post_choices = batch_policy == nullptr ? nullptr : &batch_policy->post_by_ready_count;
  if (std::vector<int> rids = chooseDecodeRids(
        world, RequestState::ReadyDecodePost, std::nullopt, post_choices); !rids.empty()) {
    return Assignment{ServerId{ServerType::Edge, -1}, DecodePostTask{std::move(rids)}};
  }

  if (const auto rid = findFirstRequest(world, RequestState::ReadyPrefillPost)) {
    const Request& request = world.requests.at(static_cast<std::size_t>(*rid));
    assert(request.remote.has_value());
    return Assignment{ServerId{ServerType::Edge, -1}, PrefillPostTask{*request.remote, *rid}};
  }

  const std::vector<int>* pre_choices = batch_policy == nullptr ? nullptr : &batch_policy->pre_by_ready_count;
  if (std::vector<int> rids = chooseDecodeRids(
        world, RequestState::ReadyDecodePre, std::nullopt, pre_choices); !rids.empty()) {
    return Assignment{ServerId{ServerType::Edge, -1}, DecodePreTask{std::move(rids)}};
  }

  if (const auto rid = findFirstRequest(world, RequestState::ReadyPrefillPre)) {
    assert(!world.clouds.empty());
    const int remote = *rid % static_cast<int>(world.clouds.size());
    return Assignment{ServerId{ServerType::Edge, -1}, PrefillPreTask{remote, *rid}};
  }

  return std::nullopt;
}

std::optional<Assignment> chooseCloudAssignment(
  const WorldState& world, int remote, int num_layers, const DecodeBatchPolicy* batch_policy) {
  const ServerState& cloud = world.clouds.at(static_cast<std::size_t>(remote));
  if (cloud.busy) {
    return std::nullopt;
  }

  const std::vector<int>* proc_choices = batch_policy == nullptr ? nullptr : &batch_policy->proc_by_ready_count;
  if (std::vector<int> rids = chooseDecodeRids(
        world, RequestState::ReadyDecodeProc, remote, proc_choices); !rids.empty()) {
    return Assignment{ServerId{ServerType::Cloud, remote}, DecodeProcTask{remote, std::move(rids)}};
  }

  if (const auto rid = findFirstRequest(world, RequestState::ReadyPrefillProc, remote)) {
    const Request& request = world.requests.at(static_cast<std::size_t>(*rid));
    assert(request.next_prefill_layer < num_layers);
    return Assignment{
      ServerId{ServerType::Cloud, remote},
      PrefillProcTask{request.next_prefill_layer, num_layers, remote, *rid},
    };
  }

  return std::nullopt;
}

std::vector<Assignment> chooseAssignments(
  const WorldState& world, int num_layers, const DecodeBatchPolicy* batch_policy) {
  assert(num_layers > 0);

  std::vector<Assignment> assignments;
  assignments.reserve(world.clouds.size() + 1);

  if (const auto edge_assignment = chooseEdgeAssignment(world, batch_policy)) {
    assignments.push_back(*edge_assignment);
  }

  for (std::size_t i = 0; i < world.clouds.size(); ++i) {
    if (const auto cloud_assignment = chooseCloudAssignment(world, static_cast<int>(i), num_layers, batch_policy)) {
      assignments.push_back(*cloud_assignment);
    }
  }

  return assignments;
}

std::vector<int> buildBatchChoices(const TimingCurve& curve, double assignment_cost, int max_batch_size) {
  assert(assignment_cost >= 0.0);
  assert(max_batch_size >= 1);

  std::vector<int> choices(static_cast<std::size_t>(max_batch_size + 1));
  int best_batch_size = 1;
  double best_cost = assignment_cost + interpolate(curve, 1);
  choices[1] = 1;

  for (int batch_size = 2; batch_size <= max_batch_size; ++batch_size) {
    const double cost = (assignment_cost + interpolate(curve, batch_size)) / batch_size;
    if (cost < best_cost) {
      best_batch_size = batch_size;
      best_cost = cost;
    }
    choices[static_cast<std::size_t>(batch_size)] = best_batch_size;
  }

  return choices;
}

} // namespace

DecodeBatchPolicy buildDecodeBatchPolicy(const TimingCurves& curves, double assignment_cost, int max_batch_size) {
  return {
    .pre_by_ready_count = buildBatchChoices(curves.decode_pre, assignment_cost, max_batch_size),
    .proc_by_ready_count = buildBatchChoices(curves.decode_proc, assignment_cost, max_batch_size),
    .post_by_ready_count = buildBatchChoices(curves.decode_post, assignment_cost, max_batch_size),
  };
}

std::vector<Assignment> chooseSingletonAssignments(const WorldState& world, int num_layers) {
  return chooseAssignments(world, num_layers, nullptr);
}

std::vector<Assignment> chooseBatchedAssignments(
  const WorldState& world, int num_layers, const DecodeBatchPolicy& batch_policy) {
  return chooseAssignments(world, num_layers, &batch_policy);
}
// ===== END src/Scheduler.cpp =====

// ===== BEGIN src/main.cpp =====
// C++20
#include <cassert>
#include <sstream>
#include <iostream>
#include <string>
#include <vector>
#include <variant>

// class Scheduler {
//   SystemConfig config_;
//   TimingCurves timing_curves_;
//   WorldState world_;
// };

// class Scheduler {
// public:
//   void onFrame(const Frame& frame);

//   std::vector<Assignment> decide(double currentTime);

// private:
//   WorldState world_;
// }

/*
read the 2 parameter lines, then N and the N warmup rows
loop:
    read one line; if it is END: exit
    parse it as timestamp t; read event count e from the next line
    read the e event lines
    update your state (completions, arrivals, transfers, FINs)
    choose assignments for currently free resources (possibly none)
    print n and the n assignment lines; flush
*/

int main() {
  std::ios_base::sync_with_stdio(false);
  std::cin.tie(nullptr);

  SystemConfig config = readSystemConfig(std::cin);
  TaskTimeTable table = readTaskTimeTable(std::cin);
  const TimingCurves curves = buildTimingCurves(table);
  const DecodeBatchPolicy batch_policy = buildDecodeBatchPolicy(curves, config.S);
  WorldState world{config.K};

  while (const auto frame = readFrame(std::cin)) {
    applyFrame(world, *frame, config.num_layers);

    const std::vector<Assignment> assignments = chooseBatchedAssignments(world, config.num_layers, batch_policy);

    for (const Assignment& assignment : assignments) {
      startAssignment(world, assignment, config.num_layers);
    }

    writeAssignments(std::cout, assignments);
    std::cout << std::flush;
  }

  return 0;
}
// ===== END src/main.cpp =====
