// Generated by scripts/generate_submission.py. Do not edit this file directly.

// Regenerate it after changing project sources.

// ===== BEGIN include/Protocol.hpp =====
#include <cstdint>
#include <iosfwd>
#include <optional>
#include <variant>
#include <vector>

/************************************/
/************** SERVERS *************/
/************************************/

enum class ServerType {
  Edge,
  Cloud
};

struct ServerId {
  ServerType type;
  int cloud_index; // Ignored when type == Edge
};

/*********************************/
/************* TASKS *************/
/*********************************/

struct PrefillPreTask {
  int remote;
  int rid;
};

struct PrefillProcTask {
  int layer_begin;
  int layer_end;
  int remote;
  int rid;
};

struct PrefillPostTask {
  int remote;
  int rid;
};

struct DecodePreTask {
  std::vector<int> rids;
};

struct DecodeProcTask {
  int remote;
  std::vector<int> rids;
};

struct DecodePostTask {
  std::vector<int> rids;
};

// TaskSpec: temporary work assigned to a computer
using TaskSpec = std::variant<
  PrefillPreTask,
  PrefillProcTask,
  PrefillPostTask,
  DecodePreTask,
  DecodeProcTask,
  DecodePostTask
>;

struct Assignment {
  ServerId server;
  TaskSpec task;
};

/**********************************/
/************* EVENTS *************/
/**********************************/

struct ArrivalEvent {
  int rid;
  int input_length;
  /* rid, input length */
};

struct TaskDoneEvent {
  ServerId server;
  TaskSpec task;
  double duration;
  /* server, task specification, duration */
};

enum class TransferDirection {
  Up,
  Down
};

enum class TransferStage {
  Prefill,
  Decode
};

// XDN <UP|DOWN> <remote> <size> <PRE|DEC> <m> <rid...>
struct TransferDoneEvent {
  TransferDirection direction;
  int remote;
  std::int64_t size_bytes;
  TransferStage stage;
  std::vector < int > rids;
  /* direction, remote, size, stage, rids */
};

struct FinishEvent {
  int rid;
  /* rid */
};

// Event: notification that something arrived or completed
using Event = std::variant<
  ArrivalEvent,
  TaskDoneEvent,
  TransferDoneEvent,
  FinishEvent
>;

/********************************/
/************* FRAME ************/
/********************************/

struct Frame {
  double timestamp;
  std::vector < Event > events;
};

std::optional < Frame > readFrame(std::istream& input);
void writeAssignments(std::ostream& output, const std::vector<Assignment>& assignments);
// ===== END include/Protocol.hpp =====

// ===== BEGIN include/SystemConfig.hpp =====
// times in ms, output rates in tokens/ms
#include <iosfwd>
#include <cstdint>

// K S latency_in_ms bandwidth_gbps bytes_per_token num_layers
// SLO1 SLO2 tp_UB tp_base dist_base w_tp w_c
struct SystemConfig {
  // Scoring parameters
  double SLO1;
  double SLO2;
  double tp_UB;
  double tp_base;
  double dist_base;
  double w_tp;
  double w_c;

  // System parameters
  double S;                   // Schedule Cost
  double latency_in_ms;
  double bandwidth_gbps;
  int K;
  int bytes_per_token;
  int num_layers;
};

double transferTime(const SystemConfig& config, std::int64_t len);
SystemConfig readSystemConfig(std::istream& input);
// ===== END include/SystemConfig.hpp =====

// ===== BEGIN include/TaskTimeTable.hpp =====
#include <iosfwd>
#include <vector>

// Read an integer N, then N rows of 7 values; no response is expected:
// batch_size  prefill_pre  prefill_proc  prefill_post  decode_pre  decode_proc  decode_post

// batch_size:    the number of requests grouped into one task
// prefill:       the input stage
// decode:        output steps

// a more advanced scheduler will use the complete task-time table, including values between listed rows.

struct TaskTimeRow {
  int batch_size; // L_in: vals are distinct positive integers in [1, 4096]

  double prefill_pre;
  double prefill_proc;
  double prefill_post;

  double decode_pre;
  double decode_proc;
  double decode_post;
};

struct TaskTimeTable {
  std::vector<TaskTimeRow> rows;
};

struct TimingPoint {
  int batch_size;
  double duration;
};

struct TimingCurve {
  std::vector < TimingPoint > points;
};

struct TimingCurves {
  TimingCurve prefill_pre;
  TimingCurve prefill_proc;
  TimingCurve prefill_post;
  TimingCurve decode_pre;
  TimingCurve decode_proc;
  TimingCurve decode_post;
};

TaskTimeTable readTaskTimeTable(std::istream& input);
TimingCurves buildTimingCurves(const TaskTimeTable& table);
double interpolate(const TimingCurve& curve, int size);
// ===== END include/TaskTimeTable.hpp =====

// ===== BEGIN include/WorldState.hpp =====
#include <cstddef>
#include <optional>
#include <vector>

// RequestState: current position of that request
enum class RequestState {
  ReadyPrefillPre,
  WaitingPrefillPreDone,
  WaitingPrefillUpload,

  ReadyPrefillProc,
  WaitingPrefillProcDone,
  WaitingPrefillDownload,

  ReadyPrefillPost,
  WaitingPrefillPostDone,

  ReadyDecodePre,
  WaitingDecodePreDone,
  WaitingDecodeUpload,

  ReadyDecodeProc,
  WaitingDecodeProcDone,
  WaitingDecodeDownload,

  ReadyDecodePost,
  WaitingDecodePostDone,

  Finished
};

// Request: persistent end-to-end workload
struct Request {
  int input_length;
  double arrival_time;

  std::optional<int> remote;
  int next_prefill_layer = 0;
  int tokens_produced = 0;
  std::optional<double> last_token_time;

  RequestState state;
};

struct ServerState  {
  bool busy = false;
};

struct WorldState {
  double current_time = 0.0;

  ServerState edge;
  std::vector<ServerState> clouds;
  std::vector<Request> requests;

  explicit WorldState(int cloud_count)
    : clouds(static_cast<std::size_t>(cloud_count)) {}
};

void applyFrame(WorldState& world, const Frame& frame, int num_layers);
void startAssignment(WorldState& world, const Assignment& assignment, int num_layers);
// ===== END include/WorldState.hpp =====

// ===== BEGIN include/SingletonScheduler.hpp =====
#include <vector>

std::vector<Assignment> chooseSingletonAssignments(const WorldState& world, int num_layers);
// ===== END include/SingletonScheduler.hpp =====

// ===== BEGIN include/DecodeBatchScheduler.hpp =====
#include <cstddef>
#include <vector>

struct DecodeBatchPolicy {
  std::vector<int> pre_by_ready_count;
  std::vector<int> proc_by_ready_count;
  std::vector<int> post_by_ready_count;
};

DecodeBatchPolicy buildDecodeBatchPolicy(const TimingCurves& curves, double assignment_cost, int max_batch_size = 4096);
int selectDecodeBatchSize(const DecodeBatchPolicy& policy, RequestState state, std::size_t ready_count);
std::vector<Assignment> chooseBatchedAssignments(
  const WorldState& world, int num_layers, const DecodeBatchPolicy& batch_policy);
// ===== END include/DecodeBatchScheduler.hpp =====

// ===== BEGIN include/ScoreAwareScheduler.hpp =====
#include <optional>
#include <vector>

enum class RequestClass {
  Prefill,
  Cold,
  Hot,
  Finished
};

struct ScoreAwareSchedulerConfig {
  DecodeBatchPolicy decode_batches;
  int target_hot_set_size;
  double slo_tdr;
  double slo_tpot;
  double waiting_weight;
};

RequestClass classifyRequest(const Request& request);
int countActiveHotSet(const WorldState& world);
ScoreAwareSchedulerConfig buildScoreAwareSchedulerConfig(
  const SystemConfig& system,
  const TimingCurves& curves,
  std::optional<int> target_hot_set_size = std::nullopt);
std::vector<Assignment> chooseScoreAwareAssignments(
  const WorldState& world, int num_layers, const ScoreAwareSchedulerConfig& config);
// ===== END include/ScoreAwareScheduler.hpp =====

// ===== BEGIN include/AdaptiveScheduler.hpp =====
#include <vector>

enum class AdaptiveScoreRegime {
  HardSlo,
  Waiting,
  Balanced,
  Throughput
};

struct AdaptiveSchedulerConfig {
  DecodeBatchPolicy baseline_decode_batches;
  DecodeBatchPolicy throughput_decode_batches;
  ScoreAwareSchedulerConfig waiting_policy;
  AdaptiveScoreRegime regime;
  int preferred_decode_batch_size;
  int preferred_cloud_batch_size;
  int target_hot_set_size;
  double estimated_decode_capacity;
  double throughput_target;
};

AdaptiveScoreRegime classifyScoreRegime(const SystemConfig& system);
double estimateDecodeCapacity(
  const SystemConfig& system, const TimingCurves& curves, int total_batch_size);
AdaptiveSchedulerConfig buildAdaptiveSchedulerConfig(
  const SystemConfig& system, const TimingCurves& curves);
std::vector<Assignment> chooseAdaptiveAssignments(
  const WorldState& world, int num_layers, const AdaptiveSchedulerConfig& config);
// ===== END include/AdaptiveScheduler.hpp =====

// ===== BEGIN include/Scheduler.hpp =====

// ===== END include/Scheduler.hpp =====

// ===== BEGIN src/SchedulerCore.hpp =====
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <optional>
#include <utility>
#include <vector>

namespace scheduler_detail {

inline std::optional<int> findFirstRequest(
  const WorldState& world, RequestState state, std::optional<int> remote = std::nullopt) {
  for (std::size_t i = 0; i < world.requests.size(); ++i) {
    const Request& request = world.requests[i];
    if (request.state == state && (!remote.has_value() || request.remote == remote)) {
      return static_cast<int>(i);
    }
  }
  return std::nullopt;
}

inline std::vector<int> findRequests(
  const WorldState& world, RequestState state, std::optional<int> remote, std::size_t limit) {
  std::vector<int> rids;
  rids.reserve(std::min(limit, world.requests.size()));
  for (std::size_t i = 0; i < world.requests.size() && rids.size() < limit; ++i) {
    const Request& request = world.requests[i];
    if (request.state == state && (!remote.has_value() || request.remote == remote)) {
      rids.push_back(static_cast<int>(i));
    }
  }
  return rids;
}

template <typename DecodeSelector>
std::vector<int> chooseDecodeRids(
  const WorldState& world,
  RequestState state,
  std::optional<int> remote,
  const DecodeSelector& selector) {
  return selector.select(world, state, remote);
}

inline std::optional<Assignment> choosePrefillPostAssignment(const WorldState& world) {
  const auto rid = findFirstRequest(world, RequestState::ReadyPrefillPost);
  if (!rid.has_value()) {
    return std::nullopt;
  }

  const Request& request = world.requests.at(static_cast<std::size_t>(*rid));
  assert(request.remote.has_value());
  return Assignment{ServerId{ServerType::Edge, -1}, PrefillPostTask{*request.remote, *rid}};
}

inline std::optional<Assignment> choosePrefillPreAssignment(const WorldState& world) {
  const auto rid = findFirstRequest(world, RequestState::ReadyPrefillPre);
  if (!rid.has_value()) {
    return std::nullopt;
  }
  assert(!world.clouds.empty());
  const int remote = *rid % static_cast<int>(world.clouds.size());
  return Assignment{ServerId{ServerType::Edge, -1}, PrefillPreTask{remote, *rid}};
}

template <typename DecodeSelector>
std::optional<Assignment> chooseDecodePreAssignment(
  const WorldState& world, const DecodeSelector& selector) {
  std::vector<int> rids = chooseDecodeRids(
    world, RequestState::ReadyDecodePre, std::nullopt, selector);
  if (rids.empty()) {
    return std::nullopt;
  }
  return Assignment{ServerId{ServerType::Edge, -1}, DecodePreTask{std::move(rids)}};
}

template <typename DecodeSelector>
std::optional<Assignment> chooseEdgeAssignment(const WorldState& world, const DecodeSelector& selector) {
  if (world.edge.busy) {
    return std::nullopt;
  }

  if (std::vector<int> rids = chooseDecodeRids(
        world, RequestState::ReadyDecodePost, std::nullopt, selector); !rids.empty()) {
    return Assignment{ServerId{ServerType::Edge, -1}, DecodePostTask{std::move(rids)}};
  }

  if (selector.preferPrefillPostBeforeDecodePre(world)) {
    if (const auto assignment = choosePrefillPostAssignment(world)) {
      return assignment;
    }
    if (selector.preferPrefillPreBeforeDecodePre(world)) {
      if (const auto assignment = choosePrefillPreAssignment(world)) {
        return assignment;
      }
    }
    if (const auto assignment = chooseDecodePreAssignment(world, selector)) {
      return assignment;
    }
  } else {
    if (const auto assignment = chooseDecodePreAssignment(world, selector)) {
      return assignment;
    }
    if (const auto assignment = choosePrefillPostAssignment(world)) {
      return assignment;
    }
  }

  if (const auto assignment = choosePrefillPreAssignment(world)) {
    return assignment;
  }

  return std::nullopt;
}

template <typename DecodeSelector>
std::optional<Assignment> chooseCloudAssignment(
  const WorldState& world, int remote, int num_layers, const DecodeSelector& selector) {
  const ServerState& cloud = world.clouds.at(static_cast<std::size_t>(remote));
  if (cloud.busy) {
    return std::nullopt;
  }

  const auto choose_prefill = [&]() -> std::optional<Assignment> {
    const auto rid = findFirstRequest(world, RequestState::ReadyPrefillProc, remote);
    if (!rid.has_value()) {
      return std::nullopt;
    }
    const Request& request = world.requests.at(static_cast<std::size_t>(*rid));
    assert(request.next_prefill_layer < num_layers);
    return Assignment{
      ServerId{ServerType::Cloud, remote},
      PrefillProcTask{request.next_prefill_layer, num_layers, remote, *rid},
    };
  };
  if (selector.preferPrefillProcBeforeDecodeProc(world, remote)) {
    if (const auto assignment = choose_prefill()) {
      return assignment;
    }
  }

  if (std::vector<int> rids = chooseDecodeRids(
        world, RequestState::ReadyDecodeProc, remote, selector); !rids.empty()) {
    return Assignment{ServerId{ServerType::Cloud, remote}, DecodeProcTask{remote, std::move(rids)}};
  }

  if (const auto assignment = choose_prefill()) {
    return assignment;
  }

  return std::nullopt;
}

template <typename DecodeSelector>
std::vector<Assignment> chooseAssignments(
  const WorldState& world, int num_layers, const DecodeSelector& selector) {
  assert(num_layers > 0);

  std::vector<Assignment> assignments;
  assignments.reserve(world.clouds.size() + 1);
  if (const auto edge_assignment = chooseEdgeAssignment(world, selector)) {
    assignments.push_back(*edge_assignment);
  }
  for (std::size_t remote = 0; remote < world.clouds.size(); ++remote) {
    if (const auto assignment = chooseCloudAssignment(world, static_cast<int>(remote), num_layers, selector)) {
      assignments.push_back(*assignment);
    }
  }
  return assignments;
}

} // namespace scheduler_detail
// ===== END src/SchedulerCore.hpp =====

// ===== BEGIN src/Protocol.cpp =====
#include <iostream>
#include <string>
#include <vector>
#include <variant>
#include <cassert>
#include <stdexcept>

std::vector<int> readRequestIds(std::istream& input) {
  int count;
  input >> count;
  assert(count >= 1);

  std::vector<int> rids(static_cast<std::size_t>(count));
  for (int& rid : rids) {
    input >> rid;
  }

  return rids;
}

ServerId readServer(std::istream& input) {
  std::string server_token;
  input >> server_token;
  if (server_token == "E") {
    return {ServerType::Edge, -1};
  }

  if (server_token.size() >= 2 && server_token.front() == 'C') {
    const int cloud_index = std::stoi(server_token.substr(1));
    return {ServerType::Cloud, cloud_index};
  }

  throw std::runtime_error("Unknown server");
}

TaskSpec readTaskSpec(std::istream& input) {
  int marker;
  std::string family, stage;
  input >> family >> stage;

  if (family == "P") {
    if (stage == "PRE") {
      PrefillPreTask task{};
      input >> task.remote >> task.rid;
      return task;
    }

    if (stage == "PROC") {
      PrefillProcTask task{};
      input
        >> task.layer_begin
        >> task.layer_end
        >> task.remote
        >> task.rid;
      return task;
    }

    if (stage == "POST") {
      PrefillPostTask task{};
      input >> task.remote >> task.rid;
      return task;
    }
  }

  if (family == "D") {
    if (stage == "PRE") {
      DecodePreTask task{};
      input >> marker;
      assert(marker == -1);
      task.rids = readRequestIds(input);
      return task;
    }

    if (stage == "PROC") {
      DecodeProcTask task{};
      input >> task.remote;
      task.rids = readRequestIds(input);
      return task;
    }

    if (stage == "POST") {
      DecodePostTask task{};
      input >> marker;
      assert(marker == -1);
      task.rids = readRequestIds(input);
      return task;
    }
  }

  throw std::runtime_error("Unknown task spec");
}

TransferDirection parseTransferDirection(const std::string& token) {
  if (token == "UP") return TransferDirection::Up;
  if (token == "DOWN") return TransferDirection::Down;
  throw std::runtime_error("Unknown transfer direction");
}

TransferStage parseTransferStage(const std::string& token) {
  if (token == "PRE") return TransferStage::Prefill;
  if (token == "DEC") return TransferStage::Decode;
  throw std::runtime_error("Unknown transfer stage");
}

Event readEvent(std::istream& input) {
  std::string type;
  input >> type;

  if (type == "ARR") {
    ArrivalEvent event{};
    input >> event.rid >> event.input_length;
    return event;
  }

  if (type == "TDN") {
    TaskDoneEvent event{};
    event.server = readServer(input);
    event.task = readTaskSpec(input);
    input >> event.duration;
    return event;
  }

  if (type == "XDN") {
    TransferDoneEvent event{};
    std::string direction_token;
    std::string stage_token;

    input
      >> direction_token
      >> event.remote
      >> event.size_bytes
      >> stage_token;

    event.direction = parseTransferDirection(direction_token);
    event.stage = parseTransferStage(stage_token);
    event.rids = readRequestIds(input);

    return event;
  }

  if (type == "FIN") {
    FinishEvent event{};
    input >> event.rid;
    return event;
  }

  throw std::runtime_error("Unknown event type");
}

std::optional<Frame> readFrame(std::istream& input) {
  std::string timestamp_token;

  if (!(input >> timestamp_token) || timestamp_token == "END") {
    return std::nullopt;
  }

  Frame frame{};
  frame.timestamp = std::stod(timestamp_token);

  int event_count;
  input >> event_count;
  assert(event_count >= 0);

  frame.events.reserve(static_cast<std::size_t>(event_count));

  for (int i = 0; i < event_count; ++i) {
    frame.events.push_back(readEvent(input));
  }

  return frame;
}

namespace {

template <typename... Visitors>
struct OutputVisitor : Visitors... {
  using Visitors::operator()...;
};

template <typename... Visitors>
OutputVisitor(Visitors...) -> OutputVisitor<Visitors...>;

void writeRequestIds(std::ostream& output, const std::vector<int>& rids) {
  output << rids.size();
  for (const int rid : rids) {
    output << ' ' << rid;
  }
}

void writeServer(std::ostream& output, const ServerId& server) {
  if (server.type == ServerType::Edge) {
    output << "E";
  } else {
    output << "C" << server.cloud_index;
  }
}

void writeTaskSpec(std::ostream& output, const TaskSpec& task) {
  std::visit(OutputVisitor{
    [&](const PrefillPreTask& value) {
      output << "P PRE " << value.remote << ' ' << value.rid;
    },
    [&](const PrefillProcTask& value) {
      output << "P PROC " << value.layer_begin << ' ' << value.layer_end << ' ' << value.remote << ' ' << value.rid;
    },
    [&](const PrefillPostTask& value) {
      output << "P POST " << value.remote << ' ' << value.rid;
    },
    [&](const DecodePreTask& value) {
      output << "D PRE -1 ";
      writeRequestIds(output, value.rids);
    },
    [&](const DecodeProcTask& value) {
      output << "D PROC " << value.remote << ' ';
      writeRequestIds(output, value.rids);
    },
    [&](const DecodePostTask& value) {
      output << "D POST -1 ";
      writeRequestIds(output, value.rids);
    },
  }, task);
}

} // namespace

void writeAssignments(std::ostream& output, const std::vector<Assignment>& assignments) {
  output << assignments.size() << '\n';

  for (const Assignment& assignment : assignments) {
    writeServer(output, assignment.server);
    output << ' ';
    writeTaskSpec(output, assignment.task);
    output << '\n';
  }
}
// ===== END src/Protocol.cpp =====

// ===== BEGIN src/SystemConfig.cpp =====
#include <istream>
#include <cassert>

// move this to correct file
double transferTime(const SystemConfig& config, std::int64_t len) {
  // for input transfer: len = L_in[i]
  // for output transfer:
  //   for output, use the per-remote computer local-to-remote transfer and
  //   per-group remote-to-local transfer sizes defined in Output Steps
  assert(config.latency_in_ms > 0);
  const std::int64_t data_bytes = len * config.bytes_per_token;
  return config.latency_in_ms + 8.0 * static_cast<double>(data_bytes)
    / (config.bandwidth_gbps * 1'000'000.0); // ms
}

SystemConfig readSystemConfig(std::istream& input) {
  SystemConfig config{};

  input >> config.K
    >> config.S
    >> config.latency_in_ms
    >> config.bandwidth_gbps
    >> config.bytes_per_token
    >> config.num_layers
    >> config.SLO1
    >> config.SLO2
    >> config.tp_UB
    >> config.tp_base
    >> config.dist_base
    >> config.w_tp
    >> config.w_c;

  return config;
}
// ===== END src/SystemConfig.cpp =====

// ===== BEGIN src/TaskTimeTable.cpp =====
#include <istream>
#include <vector>
#include <cassert>
#include <algorithm>
#include <iterator>

// Preconditions:
// - curve.points is nonempty
// - points are sorted by batch_size
// - no point has duration == -1
double interpolate(const TimingCurve& curve, int size) {
  assert(!curve.points.empty());
  if (size <= curve.points.front().batch_size) {
    return curve.points.front().duration;
  }
  if (curve.points.back().batch_size <= size) {
    return curve.points.back().duration;
  }

  const auto right = std::lower_bound(
    curve.points.begin(), curve.points.end(), size, [](const TimingPoint& point, int target) {
      return point.batch_size < target;
    });
  assert(right != curve.points.begin());
  assert(right != curve.points.end());
  if (right->batch_size == size) {
    return right->duration;
  }

  const TimingPoint& left = *std::prev(right);
  return left.duration
    + (size - left.batch_size) * (right->duration - left.duration)
    / (right->batch_size - left.batch_size);
}

namespace {

using DurationMember = double TaskTimeRow::*;

void finalizeCurve(TimingCurve& curve) {
  assert(!curve.points.empty());
  std::sort(curve.points.begin(), curve.points.end(), [](const TimingPoint& a, const TimingPoint& b) {
    return a.batch_size < b.batch_size;
  });
}

TimingCurve makeTimingCurve(const TaskTimeTable& table, DurationMember member) {
  TimingCurve curve;
  curve.points.reserve(table.rows.size());
  for (const TaskTimeRow& row : table.rows) {
    const double duration = row.*member;

    if (duration != -1.0) {
      curve.points.push_back({row.batch_size, duration});
    }
  }

  finalizeCurve(curve);
  return curve;
}

} // namespace

TimingCurves buildTimingCurves(const TaskTimeTable& table) {
  return {
    .prefill_pre  = makeTimingCurve(table, &TaskTimeRow::prefill_pre),
    .prefill_proc = makeTimingCurve(table, &TaskTimeRow::prefill_proc),
    .prefill_post = makeTimingCurve(table, &TaskTimeRow::prefill_post),
    .decode_pre   = makeTimingCurve(table, &TaskTimeRow::decode_pre),
    .decode_proc  = makeTimingCurve(table, &TaskTimeRow::decode_proc),
    .decode_post  = makeTimingCurve(table, &TaskTimeRow::decode_post),
  };
}

TaskTimeTable readTaskTimeTable(std::istream& input) {
  int n;
  input >> n;
  TaskTimeTable table;
  table.rows.reserve(n);
  for (int i = 0; i < n; i++) {
    TaskTimeRow row{};
    input >> row.batch_size;
    input >> row.prefill_pre >> row.prefill_proc >> row.prefill_post;
    input >> row.decode_pre >> row.decode_proc >> row.decode_post;
    table.rows.push_back(row);
  }
  return table;
}
// ===== END src/TaskTimeTable.cpp =====

// ===== BEGIN src/WorldState.cpp =====
#include <cassert>
#include <variant>

namespace {

template <typename... Visitors>
struct Overloaded : Visitors... {
  using Visitors::operator()...;
};

template <typename... Visitors>
Overloaded(Visitors...) -> Overloaded<Visitors...>;

Request& getRequest(WorldState& world, int rid) {
  assert(rid >= 0);
  const auto index = static_cast<std::size_t>(rid);
  assert(index < world.requests.size());
  return world.requests.at(index);
}

ServerState& getServer(WorldState& world, const ServerId& server) {
  if (server.type == ServerType::Edge) {
    return world.edge;
  }

  assert(server.cloud_index >= 0);
  const auto index = static_cast<std::size_t>(server.cloud_index);
  assert(index < world.clouds.size());
  return world.clouds.at(index);
}

void assertEdgeServer([[maybe_unused]] const ServerId& server) {
  assert(server.type == ServerType::Edge);
}

void assertCloudServer([[maybe_unused]] const ServerId& server, [[maybe_unused]] int remote) {
  assert(server.type == ServerType::Cloud);
  assert(server.cloud_index == remote);
}

void assertRequestRemote([[maybe_unused]] const Request& request, [[maybe_unused]] int remote) {
  assert(request.remote.has_value());
  assert(*request.remote == remote);
}

void applyArrival(WorldState& world, const ArrivalEvent& arrival) {
  assert(arrival.rid >= 0);
  assert(arrival.input_length > 0);

  [[maybe_unused]] const auto rid = static_cast<std::size_t>(arrival.rid);
  assert(rid == world.requests.size());

  world.requests.push_back({
    .input_length = arrival.input_length,
    .arrival_time = world.current_time,
    .remote = std::nullopt,
    .next_prefill_layer = 0,
    .tokens_produced = 0,
    .last_token_time = std::nullopt,
    .state = RequestState::ReadyPrefillPre,
  });
}

void applyTaskDone(WorldState& world, const TaskDoneEvent& event, int num_layers) {
  assert(num_layers > 0);

  ServerState& server = getServer(world, event.server);
  assert(server.busy);

  std::visit(Overloaded{
    [&](const PrefillPreTask& task) {
      assertEdgeServer(event.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::WaitingPrefillPreDone);
      assertRequestRemote(request, task.remote);
      request.state = RequestState::WaitingPrefillUpload;
    },
    [&](const PrefillProcTask& task) {
      assertCloudServer(event.server, task.remote);
      assert(task.layer_begin >= 0);
      assert(task.layer_begin < task.layer_end);
      assert(task.layer_end <= num_layers);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::WaitingPrefillProcDone);
      assertRequestRemote(request, task.remote);
      assert(request.next_prefill_layer == task.layer_begin);

      request.next_prefill_layer = task.layer_end;
      request.state = task.layer_end == num_layers
        ? RequestState::WaitingPrefillDownload
        : RequestState::ReadyPrefillProc;
    },
    [&](const PrefillPostTask& task) {
      assertEdgeServer(event.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::WaitingPrefillPostDone);
      assertRequestRemote(request, task.remote);
      request.state = RequestState::ReadyDecodePre;
    },
    [&](const DecodePreTask& task) {
      assertEdgeServer(event.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        Request& request = getRequest(world, rid);
        assert(request.state == RequestState::WaitingDecodePreDone);
        assert(request.remote.has_value());
        request.state = RequestState::WaitingDecodeUpload;
      }
    },
    [&](const DecodeProcTask& task) {
      assertCloudServer(event.server, task.remote);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        Request& request = getRequest(world, rid);
        assert(request.state == RequestState::WaitingDecodeProcDone);
        assertRequestRemote(request, task.remote);
        request.state = RequestState::WaitingDecodeDownload;
      }
    },
    [&](const DecodePostTask& task) {
      assertEdgeServer(event.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        Request& request = getRequest(world, rid);
        assert(request.state == RequestState::WaitingDecodePostDone);
        ++request.tokens_produced;
        request.last_token_time = world.current_time;
        request.state = RequestState::ReadyDecodePre;
      }
    },
  }, event.task);

  server.busy = false;
}

void applyTransferDone(WorldState& world, const TransferDoneEvent& event) {
  assert(event.remote >= 0);
  assert(static_cast<std::size_t>(event.remote) < world.clouds.size());
  assert(!event.rids.empty());

  if (event.stage == TransferStage::Prefill) {
    assert(event.rids.size() == 1);

    Request& request = getRequest(world, event.rids.front());
    assertRequestRemote(request, event.remote);

    if (event.direction == TransferDirection::Up) {
      assert(request.state == RequestState::WaitingPrefillUpload);
      request.state = RequestState::ReadyPrefillProc;
    } else {
      assert(request.state == RequestState::WaitingPrefillDownload);
      request.state = RequestState::ReadyPrefillPost;
    }

    return;
  }

  for (const int rid : event.rids) {
    Request& request = getRequest(world, rid);
    assertRequestRemote(request, event.remote);

    if (event.direction == TransferDirection::Up) {
      assert(request.state == RequestState::WaitingDecodeUpload);
      request.state = RequestState::ReadyDecodeProc;
    } else {
      assert(request.state == RequestState::WaitingDecodeDownload);
      request.state = RequestState::ReadyDecodePost;
    }
  }
}

void applyFinish(WorldState& world, const FinishEvent& finish) {
  Request& request = getRequest(world, finish.rid);
  assert(request.state == RequestState::ReadyDecodePre);
  assert(request.tokens_produced > 0);
  request.state = RequestState::Finished;
}

} // namespace

void applyFrame(WorldState& world, const Frame& frame, int num_layers) {
  assert(frame.timestamp >= world.current_time);
  world.current_time = frame.timestamp;

  // FIN is deliberately deferred. The statement guarantees that it appears
  // in the same frame as the final D POST TDN, and frame line order carries no
  // priority. Applying all other events first ensures Finished always wins.
  for (const Event& event : frame.events) {
    if (const ArrivalEvent* arrival = std::get_if<ArrivalEvent>(&event)) {
      applyArrival(world, *arrival);
    } else if (const TaskDoneEvent* task_done = std::get_if<TaskDoneEvent>(&event)) {
      applyTaskDone(world, *task_done, num_layers);
    } else if (const TransferDoneEvent* transfer_done = std::get_if<TransferDoneEvent>(&event)) {
      applyTransferDone(world, *transfer_done);
    }
  }

  for (const Event& event : frame.events) {
    if (const FinishEvent* finish = std::get_if<FinishEvent>(&event)) {
      applyFinish(world, *finish);
    }
  }
}

void startAssignment(WorldState& world, const Assignment& assignment, [[maybe_unused]] int num_layers) {
  assert(num_layers > 0);

  ServerState& server = getServer(world, assignment.server);
  assert(!server.busy);

  std::visit(Overloaded{
    [&](const PrefillPreTask& task) {
      assertEdgeServer(assignment.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::ReadyPrefillPre);
      assert(!request.remote.has_value());

      assert(task.remote >= 0);
      assert(static_cast<std::size_t>(task.remote) < world.clouds.size());

      request.remote = task.remote;
      request.state = RequestState::WaitingPrefillPreDone;
    },
    [&](const PrefillProcTask& task) {
      assertCloudServer(assignment.server, task.remote);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::ReadyPrefillProc);
      assertRequestRemote(request, task.remote);

      assert(task.layer_begin == request.next_prefill_layer);
      assert(task.layer_begin >= 0);
      assert(task.layer_begin < task.layer_end);
      assert(task.layer_end <= num_layers);

      request.state = RequestState::WaitingPrefillProcDone;
    },
    [&](const PrefillPostTask& task) {
      assertEdgeServer(assignment.server);

      Request& request = getRequest(world, task.rid);
      assert(request.state == RequestState::ReadyPrefillPost);
      assertRequestRemote(request, task.remote);

      request.state = RequestState::WaitingPrefillPostDone;
    },
    [&](const DecodePreTask& task) {
      assertEdgeServer(assignment.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        [[maybe_unused]] const Request& request = getRequest(world, rid);
        assert(request.state == RequestState::ReadyDecodePre);
        assert(request.remote.has_value());
      }

      for (const int rid : task.rids) {
        getRequest(world, rid).state = RequestState::WaitingDecodePreDone;
      }
    },
    [&](const DecodeProcTask& task) {
      assertCloudServer(assignment.server, task.remote);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        [[maybe_unused]] const Request& request = getRequest(world, rid);
        assert(request.state == RequestState::ReadyDecodeProc);
        assertRequestRemote(request, task.remote);
      }

      for (const int rid : task.rids) {
        getRequest(world, rid).state = RequestState::WaitingDecodeProcDone;
      }
    },
    [&](const DecodePostTask& task) {
      assertEdgeServer(assignment.server);
      assert(!task.rids.empty());

      for (const int rid : task.rids) {
        [[maybe_unused]] const Request& request = getRequest(world, rid);
        assert(request.state == RequestState::ReadyDecodePost);
        assert(request.remote.has_value());
      }

      for (const int rid : task.rids) {
        getRequest(world, rid).state = RequestState::WaitingDecodePostDone;
      }
    },
  }, assignment.task);

  server.busy = true;
}
// ===== END src/WorldState.cpp =====

// ===== BEGIN src/SingletonScheduler.cpp =====
#include <cstddef>

namespace {

class SingletonDecodeSelector {
public:
  std::vector<int> select(
    const WorldState& world, RequestState state, std::optional<int> remote) const {
    return scheduler_detail::findRequests(world, state, remote, 1);
  }

  bool preferPrefillPostBeforeDecodePre(const WorldState&) const {
    return true;
  }

  bool preferPrefillPreBeforeDecodePre(const WorldState&) const {
    return false;
  }

  bool preferPrefillProcBeforeDecodeProc(const WorldState&, int) const {
    return false;
  }
};

} // namespace

std::vector<Assignment> chooseSingletonAssignments(const WorldState& world, int num_layers) {
  return scheduler_detail::chooseAssignments(world, num_layers, SingletonDecodeSelector{});
}
// ===== END src/SingletonScheduler.cpp =====

// ===== BEGIN src/DecodeBatchScheduler.cpp =====
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <limits>
#include <vector>

namespace {

std::vector<int> buildBatchChoices(const TimingCurve& curve, double assignment_cost, int max_batch_size) {
  assert(assignment_cost >= 0.0);
  assert(max_batch_size >= 1);

  std::vector<int> choices(static_cast<std::size_t>(max_batch_size + 1));
  int best_batch_size = 1;
  double best_cost = assignment_cost + interpolate(curve, 1);
  choices[1] = 1;

  for (int batch_size = 2; batch_size <= max_batch_size; ++batch_size) {
    const double cost = (assignment_cost + interpolate(curve, batch_size)) / batch_size;
    if (cost < best_cost) {
      best_batch_size = batch_size;
      best_cost = cost;
    }
    choices[static_cast<std::size_t>(batch_size)] = best_batch_size;
  }
  return choices;
}

class BatchedDecodeSelector {
public:
  explicit BatchedDecodeSelector(const DecodeBatchPolicy& policy)
    : policy_(policy) {}

  std::vector<int> select(
    const WorldState& world, RequestState state, std::optional<int> remote) const {
    std::vector<int> rids = scheduler_detail::findRequests(
      world, state, remote, std::numeric_limits<std::size_t>::max());
    if (!rids.empty()) {
      rids.resize(static_cast<std::size_t>(selectDecodeBatchSize(policy_, state, rids.size())));
    }
    return rids;
  }

  bool preferPrefillPostBeforeDecodePre(const WorldState&) const {
    return true;
  }

  bool preferPrefillPreBeforeDecodePre(const WorldState&) const {
    return false;
  }

  bool preferPrefillProcBeforeDecodeProc(const WorldState&, int) const {
    return false;
  }

private:
  const DecodeBatchPolicy& policy_;
};

} // namespace

int selectDecodeBatchSize(const DecodeBatchPolicy& policy, RequestState state, std::size_t ready_count) {
  assert(ready_count > 0);
  const std::vector<int>* choices = nullptr;
  if (state == RequestState::ReadyDecodePre) {
    choices = &policy.pre_by_ready_count;
  } else if (state == RequestState::ReadyDecodeProc) {
    choices = &policy.proc_by_ready_count;
  } else {
    assert(state == RequestState::ReadyDecodePost);
    choices = &policy.post_by_ready_count;
  }

  assert(choices->size() > 1);
  const std::size_t index = std::min(ready_count, choices->size() - 1);
  return choices->at(index);
}

DecodeBatchPolicy buildDecodeBatchPolicy(const TimingCurves& curves, double assignment_cost, int max_batch_size) {
  return {
    .pre_by_ready_count = buildBatchChoices(curves.decode_pre, assignment_cost, max_batch_size),
    .proc_by_ready_count = buildBatchChoices(curves.decode_proc, assignment_cost, max_batch_size),
    .post_by_ready_count = buildBatchChoices(curves.decode_post, assignment_cost, max_batch_size),
  };
}

std::vector<Assignment> chooseBatchedAssignments(
  const WorldState& world, int num_layers, const DecodeBatchPolicy& batch_policy) {
  return scheduler_detail::chooseAssignments(world, num_layers, BatchedDecodeSelector{batch_policy});
}
// ===== END src/DecodeBatchScheduler.cpp =====

// ===== BEGIN src/ScoreAwareScheduler.cpp =====
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <limits>
#include <optional>
#include <utility>
#include <vector>

namespace {

bool isPrefillState(RequestState state) {
  switch (state) {
    case RequestState::ReadyPrefillPre:
    case RequestState::WaitingPrefillPreDone:
    case RequestState::WaitingPrefillUpload:
    case RequestState::ReadyPrefillProc:
    case RequestState::WaitingPrefillProcDone:
    case RequestState::WaitingPrefillDownload:
    case RequestState::ReadyPrefillPost:
    case RequestState::WaitingPrefillPostDone:
      return true;
    default:
      return false;
  }
}

bool isColdAdmissionInFlight(const Request& request) {
  return classifyRequest(request) == RequestClass::Cold
    && request.state != RequestState::ReadyDecodePre;
}

double normalizedExcess(double elapsed, double target) {
  assert(target > 0.0);
  return std::max(0.0, elapsed / target - 1.0);
}

double hotUrgency(const WorldState& world, const Request& request, double slo_tpot) {
  assert(classifyRequest(request) == RequestClass::Hot);
  assert(request.last_token_time.has_value());
  const double last_token_time = request.last_token_time.value_or(request.arrival_time);
  return (world.current_time - last_token_time) / slo_tpot;
}

double coldUrgency(const WorldState& world, const Request& request, double slo_tdr) {
  return (world.current_time - request.arrival_time) / slo_tdr;
}

struct Candidate {
  int rid;
  RequestClass request_class;
  double urgency;
};

class ScoreAwareDecodeSelector {
public:
  explicit ScoreAwareDecodeSelector(const ScoreAwareSchedulerConfig& config)
    : config_(config) {}

  std::vector<int> select(
    const WorldState& world, RequestState state, std::optional<int> remote) const {
    const std::vector<int> ready = scheduler_detail::findRequests(
      world, state, remote, std::numeric_limits<std::size_t>::max());
    std::vector<Candidate> candidates;
    candidates.reserve(ready.size());

    for (const int rid : ready) {
      const Request& request = world.requests.at(static_cast<std::size_t>(rid));
      const RequestClass request_class = classifyRequest(request);
      assert(request_class == RequestClass::Cold || request_class == RequestClass::Hot);
      const double urgency = request_class == RequestClass::Hot
        ? hotUrgency(world, request, config_.slo_tpot)
        : coldUrgency(world, request, config_.slo_tdr);
      candidates.push_back({rid, request_class, urgency});
    }

    std::sort(candidates.begin(), candidates.end(), [](const Candidate& left, const Candidate& right) {
      if (left.request_class != right.request_class) {
        return left.request_class == RequestClass::Hot;
      }
      if (left.urgency != right.urgency) {
        return left.urgency > right.urgency;
      }
      return left.rid < right.rid;
    });

    int remaining_cold_admissions = state == RequestState::ReadyDecodePre
      ? std::max(0, config_.target_hot_set_size - countActiveHotSet(world))
      : std::numeric_limits<int>::max();
    std::vector<int> selected;
    selected.reserve(candidates.size());
    for (const Candidate& candidate : candidates) {
      if (state == RequestState::ReadyDecodePre && candidate.request_class == RequestClass::Cold) {
        if (remaining_cold_admissions == 0) {
          continue;
        }
        --remaining_cold_admissions;
      }
      selected.push_back(candidate.rid);
    }

    if (!selected.empty()) {
      selected.resize(static_cast<std::size_t>(
        selectDecodeBatchSize(config_.decode_batches, state, selected.size())));
    }
    return selected;
  }

  bool preferPrefillPostBeforeDecodePre(const WorldState& world) const {
    double tdr_pressure = 0.0;
    double tpot_pressure = 0.0;
    for (const Request& request : world.requests) {
      if (request.state == RequestState::ReadyPrefillPost) {
        tdr_pressure = std::max(
          tdr_pressure,
          normalizedExcess(world.current_time - request.arrival_time, config_.slo_tdr));
      }
      if (request.state == RequestState::ReadyDecodePre && classifyRequest(request) == RequestClass::Hot) {
        tpot_pressure = std::max(
          tpot_pressure,
          normalizedExcess(
            world.current_time - request.last_token_time.value_or(request.arrival_time),
            config_.slo_tpot));
      }
    }
    if (config_.waiting_weight > 0.0 && (tdr_pressure > 0.0 || tpot_pressure > 0.0)) {
      return tdr_pressure > 0.0 && tdr_pressure >= tpot_pressure;
    }
    return countActiveHotSet(world) < config_.target_hot_set_size;
  }

  bool preferPrefillPreBeforeDecodePre(const WorldState&) const {
    return false;
  }

  bool preferPrefillProcBeforeDecodeProc(const WorldState&, int) const {
    return false;
  }

private:
  const ScoreAwareSchedulerConfig& config_;
};

} // namespace

RequestClass classifyRequest(const Request& request) {
  if (request.state == RequestState::Finished) {
    return RequestClass::Finished;
  }
  if (isPrefillState(request.state)) {
    return RequestClass::Prefill;
  }
  return request.tokens_produced == 0 ? RequestClass::Cold : RequestClass::Hot;
}

int countActiveHotSet(const WorldState& world) {
  return static_cast<int>(std::count_if(
    world.requests.begin(), world.requests.end(), [](const Request& request) {
      return classifyRequest(request) == RequestClass::Hot || isColdAdmissionInFlight(request);
    }));
}

ScoreAwareSchedulerConfig buildScoreAwareSchedulerConfig(
  const SystemConfig& system,
  const TimingCurves& curves,
  std::optional<int> target_hot_set_size) {
  DecodeBatchPolicy decode_batches = buildDecodeBatchPolicy(curves, system.S);
  const double singleton_decode_cycle =
    3.0 * system.S
    + interpolate(curves.decode_pre, 1)
    + interpolate(curves.decode_proc, 1)
    + interpolate(curves.decode_post, 1)
    + 2.0 * transferTime(system, 1);
  const double tpot_slack = std::clamp(system.SLO2 / singleton_decode_cycle, 0.5, 4.0);
  const double concurrency_per_cloud = (4.0 + 28.0 * system.w_tp) * tpot_slack;
  const int horizon = std::clamp(
    static_cast<int>(std::ceil(system.K * concurrency_per_cloud)), 1, 4096);
  const int curve_target = std::max({
    selectDecodeBatchSize(decode_batches, RequestState::ReadyDecodePre, horizon),
    selectDecodeBatchSize(decode_batches, RequestState::ReadyDecodeProc, horizon),
    selectDecodeBatchSize(decode_batches, RequestState::ReadyDecodePost, horizon),
  });
  const int derived_target = std::max(2 * system.K, curve_target);
  const int target = target_hot_set_size.value_or(derived_target);
  assert(target >= 1);
  return {
    .decode_batches = std::move(decode_batches),
    .target_hot_set_size = target,
    .slo_tdr = system.SLO1,
    .slo_tpot = system.SLO2,
    .waiting_weight = system.w_c,
  };
}

std::vector<Assignment> chooseScoreAwareAssignments(
  const WorldState& world, int num_layers, const ScoreAwareSchedulerConfig& config) {
  assert(config.target_hot_set_size >= 1);
  assert(config.slo_tdr > 0.0);
  assert(config.slo_tpot > 0.0);
  return scheduler_detail::chooseAssignments(world, num_layers, ScoreAwareDecodeSelector{config});
}
// ===== END src/ScoreAwareScheduler.cpp =====

// ===== BEGIN src/AdaptiveScheduler.cpp =====
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <limits>
#include <optional>
#include <utility>
#include <vector>

namespace {

constexpr int max_request_count = 2000;
constexpr int pipeline_batch_count = 4;

bool hasPrefillWork(const WorldState& world) {
  return std::any_of(world.requests.begin(), world.requests.end(), [](const Request& request) {
    return classifyRequest(request) == RequestClass::Prefill;
  });
}

int countDecodePopulation(const WorldState& world) {
  return static_cast<int>(std::count_if(
    world.requests.begin(), world.requests.end(), [](const Request& request) {
      const RequestClass request_class = classifyRequest(request);
      return request_class == RequestClass::Cold || request_class == RequestClass::Hot;
    }));
}

bool hasPendingDecodeUpload(const WorldState& world, std::optional<int> remote) {
  return std::any_of(world.requests.begin(), world.requests.end(), [&](const Request& request) {
    const bool matches_remote = !remote.has_value() || request.remote == remote;
    return matches_remote
      && (request.state == RequestState::WaitingDecodePreDone
        || request.state == RequestState::WaitingDecodeUpload);
  });
}

bool hasPendingDecodeDownload(const WorldState& world) {
  return std::any_of(world.requests.begin(), world.requests.end(), [](const Request& request) {
    return request.state == RequestState::ReadyDecodeProc
      || request.state == RequestState::WaitingDecodeProcDone
      || request.state == RequestState::WaitingDecodeDownload;
  });
}

void capBatchChoices(std::vector<int>& choices, int cap) {
  assert(cap >= 1);
  for (std::size_t ready_count = 1; ready_count < choices.size(); ++ready_count) {
    choices[ready_count] = std::min(choices[ready_count], cap);
  }
}

DecodeBatchPolicy capDecodeBatches(
  DecodeBatchPolicy policy, int total_batch_size, int cloud_batch_size) {
  capBatchChoices(policy.pre_by_ready_count, total_batch_size);
  capBatchChoices(policy.proc_by_ready_count, cloud_batch_size);
  capBatchChoices(policy.post_by_ready_count, total_batch_size);
  return policy;
}

class ThroughputDecodeSelector {
public:
  explicit ThroughputDecodeSelector(const AdaptiveSchedulerConfig& config)
    : config_(config) {}

  std::vector<int> select(
    const WorldState& world, RequestState state, std::optional<int> remote) const {
    std::vector<int> ready = scheduler_detail::findRequests(
      world, state, remote, std::numeric_limits<std::size_t>::max());
    if (ready.empty() || shouldWaitForBatch(world, state, remote, ready.size())) {
      return {};
    }

    if (state == RequestState::ReadyDecodePre) {
      const int available_admissions =
        std::max(0, config_.target_hot_set_size - countActiveHotSet(world));
      int remaining_admissions = available_admissions;
      ready.erase(std::remove_if(ready.begin(), ready.end(), [&](int rid) {
        const Request& request = world.requests.at(static_cast<std::size_t>(rid));
        if (classifyRequest(request) != RequestClass::Cold) {
          return false;
        }
        if (remaining_admissions == 0) {
          return true;
        }
        --remaining_admissions;
        return false;
      }), ready.end());
    }

    if (!ready.empty()) {
      ready.resize(static_cast<std::size_t>(
        selectDecodeBatchSize(config_.throughput_decode_batches, state, ready.size())));
    }
    return ready;
  }

  bool preferPrefillPostBeforeDecodePre(const WorldState&) const {
    return true;
  }

  bool preferPrefillPreBeforeDecodePre(const WorldState& world) const {
    return countDecodePopulation(world) < config_.target_hot_set_size;
  }

  bool preferPrefillProcBeforeDecodeProc(const WorldState& world, int) const {
    return countDecodePopulation(world) < config_.target_hot_set_size;
  }

private:
  bool shouldWaitForBatch(
    const WorldState& world,
    RequestState state,
    std::optional<int> remote,
    std::size_t ready_count) const {
    const int preferred_size = state == RequestState::ReadyDecodeProc
      ? config_.preferred_cloud_batch_size
      : config_.preferred_decode_batch_size;
    if (ready_count >= static_cast<std::size_t>(preferred_size)) {
      return false;
    }
    if (state == RequestState::ReadyDecodePre) {
      return countDecodePopulation(world) < config_.target_hot_set_size && hasPrefillWork(world);
    }
    if (state == RequestState::ReadyDecodeProc) {
      return hasPendingDecodeUpload(world, remote);
    }
    assert(state == RequestState::ReadyDecodePost);
    return hasPendingDecodeDownload(world);
  }

  const AdaptiveSchedulerConfig& config_;
};

} // namespace

AdaptiveScoreRegime classifyScoreRegime(const SystemConfig& system) {
  assert(system.w_tp >= 0.0);
  assert(system.w_c >= 0.0);
  if (system.dist_base == 0.0 && system.w_c >= 0.1) {
    return AdaptiveScoreRegime::HardSlo;
  }
  if (system.w_tp >= 0.7) {
    return AdaptiveScoreRegime::Throughput;
  }
  if (system.w_c >= 0.7) {
    return AdaptiveScoreRegime::Waiting;
  }
  return AdaptiveScoreRegime::Balanced;
}

double estimateDecodeCapacity(
  const SystemConfig& system, const TimingCurves& curves, int total_batch_size) {
  assert(total_batch_size >= 1);
  const int active_clouds = std::min(system.K, total_batch_size);
  const int cloud_batch_size = (total_batch_size + active_clouds - 1) / active_clouds;
  const double edge_service_time =
    2.0 * system.S
    + interpolate(curves.decode_pre, total_batch_size)
    + interpolate(curves.decode_post, total_batch_size);
  const double cloud_service_time = system.S + interpolate(curves.decode_proc, cloud_batch_size);
  const double serialized_bytes_time =
    8.0 * static_cast<double>(total_batch_size) * system.bytes_per_token
    / (system.bandwidth_gbps * 1'000'000.0);
  const double link_service_time = active_clouds * system.latency_in_ms + serialized_bytes_time;
  const double bottleneck_time = std::max({edge_service_time, cloud_service_time, link_service_time});
  return total_batch_size / bottleneck_time;
}

AdaptiveSchedulerConfig buildAdaptiveSchedulerConfig(
  const SystemConfig& system, const TimingCurves& curves) {
  DecodeBatchPolicy baseline = buildDecodeBatchPolicy(curves, system.S);
  const AdaptiveScoreRegime regime = classifyScoreRegime(system);
  const std::optional<int> waiting_target = regime == AdaptiveScoreRegime::HardSlo
    ? std::optional<int>{system.K}
    : std::nullopt;
  const ScoreAwareSchedulerConfig waiting_policy =
    buildScoreAwareSchedulerConfig(system, curves, waiting_target);
  const double safety_margin = 1.05 + 0.1 * system.w_tp;
  const double throughput_target = system.tp_UB * safety_margin;

  int preferred_batch_size = 1;
  double preferred_capacity = estimateDecodeCapacity(system, curves, 1);
  bool reached_target = preferred_capacity >= throughput_target;
  for (int batch_size = 2; batch_size <= max_request_count; ++batch_size) {
    const double capacity = estimateDecodeCapacity(system, curves, batch_size);
    if (!reached_target && capacity > preferred_capacity) {
      preferred_batch_size = batch_size;
      preferred_capacity = capacity;
    }
    if (!reached_target && capacity >= throughput_target) {
      preferred_batch_size = batch_size;
      preferred_capacity = capacity;
      reached_target = true;
    }
  }

  const int cloud_batch_size =
    (preferred_batch_size + std::min(system.K, preferred_batch_size) - 1)
    / std::min(system.K, preferred_batch_size);
  const int throughput_hot_target = std::min(
    max_request_count,
    std::max(2 * system.K, pipeline_batch_count * preferred_batch_size));
  const int hot_target = regime == AdaptiveScoreRegime::Throughput
    ? throughput_hot_target
    : waiting_policy.target_hot_set_size;

  return {
    .baseline_decode_batches = baseline,
    .throughput_decode_batches =
      capDecodeBatches(std::move(baseline), preferred_batch_size, cloud_batch_size),
    .waiting_policy = waiting_policy,
    .regime = regime,
    .preferred_decode_batch_size = preferred_batch_size,
    .preferred_cloud_batch_size = cloud_batch_size,
    .target_hot_set_size = hot_target,
    .estimated_decode_capacity = preferred_capacity,
    .throughput_target = throughput_target,
  };
}

std::vector<Assignment> chooseAdaptiveAssignments(
  const WorldState& world, int num_layers, const AdaptiveSchedulerConfig& config) {
  if (config.regime == AdaptiveScoreRegime::Balanced) {
    return chooseBatchedAssignments(world, num_layers, config.baseline_decode_batches);
  }
  if (config.regime == AdaptiveScoreRegime::HardSlo
      || config.regime == AdaptiveScoreRegime::Waiting) {
    return chooseScoreAwareAssignments(world, num_layers, config.waiting_policy);
  }
  return scheduler_detail::chooseAssignments(world, num_layers, ThroughputDecodeSelector{config});
}
// ===== END src/AdaptiveScheduler.cpp =====

// ===== BEGIN src/main.cpp =====
// C++20
#include <cassert>
#include <sstream>
#include <iostream>
#include <string>
#include <vector>
#include <variant>

// class Scheduler {
//   SystemConfig config_;
//   TimingCurves timing_curves_;
//   WorldState world_;
// };

// class Scheduler {
// public:
//   void onFrame(const Frame& frame);

//   std::vector<Assignment> decide(double currentTime);

// private:
//   WorldState world_;
// }

/*
read the 2 parameter lines, then N and the N warmup rows
loop:
    read one line; if it is END: exit
    parse it as timestamp t; read event count e from the next line
    read the e event lines
    update your state (completions, arrivals, transfers, FINs)
    choose assignments for currently free resources (possibly none)
    print n and the n assignment lines; flush
*/

int main() {
  std::ios_base::sync_with_stdio(false);
  std::cin.tie(nullptr);

  SystemConfig config = readSystemConfig(std::cin);
  TaskTimeTable table = readTaskTimeTable(std::cin);
  const TimingCurves curves = buildTimingCurves(table);
  const AdaptiveSchedulerConfig scheduler_config = buildAdaptiveSchedulerConfig(config, curves);
  WorldState world{config.K};

  while (const auto frame = readFrame(std::cin)) {
    applyFrame(world, *frame, config.num_layers);

    const std::vector<Assignment> assignments =
      chooseAdaptiveAssignments(world, config.num_layers, scheduler_config);

    for (const Assignment& assignment : assignments) {
      startAssignment(world, assignment, config.num_layers);
    }

    writeAssignments(std::cout, assignments);
    std::cout << std::flush;
  }

  return 0;
}
// ===== END src/main.cpp =====
